# Generated by Django 4.2.7 on 2024-11-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='myapp_good',
        ),
    ]
