# Generated by Django 4.2.7 on 2024-11-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_good_alter_products_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='good',
            table='myapp_good',
        ),
    ]
